In [2]:
import tensorflow as tf
import numpy as np

# Generate 10 random values for x and y

In [3]:
np.random.seed(42)
x = np.array([np.random.randint(0, 100, 10),np.random.randint(0, 100, 10)])

In [4]:
x

array([[51, 92, 14, 71, 60, 20, 82, 86, 74, 74],
       [87, 99, 23,  2, 21, 52,  1, 87, 29, 37]])

In [5]:
x = x.reshape(10, 2)

In [6]:
x.shape

(10, 2)

In [7]:
x[:, 0]

array([51, 14, 60, 82, 74, 87, 23, 21,  1, 29])

# Generate z for the above values

In [8]:
z = 5 * x[:, 0] - 3 * x[:, 1] + 7

In [9]:
z

array([ -14, -136,  247,  159,  155,  145,  116,  -44, -249,   41])

In [10]:
z.shape

(10,)

# Create a model with 2 inputs to accept x and y (x) and predict z

In [11]:
model = tf.keras.Sequential(
    tf.keras.layers.Dense(units=1, input_shape=[2])
)

In [12]:
model.compile(
    loss='mean_squared_error',
    optimizer=tf.keras.optimizers.Adam(0.1)
)

# Model summary

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [14]:
hist = model.fit(x, z, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 285ms/step - loss: 22704.5664
Epoch 2/1000
1/1 [==============================] - 0s 4ms/step - loss: 21255.8594
Epoch 3/1000
1/1 [==============================] - 0s 6ms/step - loss: 20086.4727
Epoch 4/1000
1/1 [==============================] - 0s 4ms/step - loss: 19133.5566
Epoch 5/1000
1/1 [==============================] - 0s 8ms/step - loss: 18276.2773
Epoch 6/1000
1/1 [==============================] - 0s 4ms/step - loss: 17443.9004
Epoch 7/1000
1/1 [==============================] - 0s 7ms/step - loss: 16622.0977
Epoch 8/1000
1/1 [==============================] - 0s 6ms/step - loss: 15811.9551
Epoch 9/1000
1/1 [==============================] - 0s 6ms/step - loss: 15016.4189
Epoch 10/1000
1/1 [==============================] - 0s 4ms/step - loss: 14237.9795
Epoch 11/1000
1/1 [==============================] - 0s 6ms/step - loss: 13478.4746
Epoch 12/1000
1/1 [==============================] - 0s 4ms/step - loss: 12739.2627

1/1 [==============================] - 0s 5ms/step - loss: 17.7094
Epoch 101/1000
1/1 [==============================] - 0s 7ms/step - loss: 17.3954
Epoch 102/1000
1/1 [==============================] - 0s 5ms/step - loss: 17.0988
Epoch 103/1000
1/1 [==============================] - 0s 4ms/step - loss: 16.8203
Epoch 104/1000
1/1 [==============================] - 0s 6ms/step - loss: 16.5606
Epoch 105/1000
1/1 [==============================] - 0s 6ms/step - loss: 16.3198
Epoch 106/1000
1/1 [==============================] - 0s 7ms/step - loss: 16.0977
Epoch 107/1000
1/1 [==============================] - 0s 15ms/step - loss: 15.8942
Epoch 108/1000
1/1 [==============================] - 0s 6ms/step - loss: 15.7088
Epoch 109/1000
1/1 [==============================] - 0s 5ms/step - loss: 15.5405
Epoch 110/1000
1/1 [==============================] - 0s 7ms/step - loss: 15.3887
Epoch 111/1000
1/1 [==============================] - 0s 5ms/step - loss: 15.2522
Epoch 112/1000
1/1 [==========

1/1 [==============================] - 0s 5ms/step - loss: 10.9861
Epoch 201/1000
1/1 [==============================] - 0s 4ms/step - loss: 10.9431
Epoch 202/1000
1/1 [==============================] - 0s 7ms/step - loss: 10.9001
Epoch 203/1000
1/1 [==============================] - 0s 5ms/step - loss: 10.8571
Epoch 204/1000
1/1 [==============================] - 0s 7ms/step - loss: 10.8142
Epoch 205/1000
1/1 [==============================] - 0s 7ms/step - loss: 10.7714
Epoch 206/1000
1/1 [==============================] - 0s 5ms/step - loss: 10.7286
Epoch 207/1000
1/1 [==============================] - 0s 4ms/step - loss: 10.6859
Epoch 208/1000
1/1 [==============================] - 0s 4ms/step - loss: 10.6432
Epoch 209/1000
1/1 [==============================] - 0s 6ms/step - loss: 10.6006
Epoch 210/1000
1/1 [==============================] - 0s 5ms/step - loss: 10.5580
Epoch 211/1000
1/1 [==============================] - 0s 5ms/step - loss: 10.5155
Epoch 212/1000
1/1 [===========

Epoch 301/1000
1/1 [==============================] - 0s 3ms/step - loss: 7.0162
Epoch 302/1000
1/1 [==============================] - 0s 7ms/step - loss: 6.9816
Epoch 303/1000
1/1 [==============================] - 0s 7ms/step - loss: 6.9471
Epoch 304/1000
1/1 [==============================] - 0s 5ms/step - loss: 6.9128
Epoch 305/1000
1/1 [==============================] - 0s 6ms/step - loss: 6.8784
Epoch 306/1000
1/1 [==============================] - 0s 6ms/step - loss: 6.8443
Epoch 307/1000
1/1 [==============================] - 0s 7ms/step - loss: 6.8102
Epoch 308/1000
1/1 [==============================] - 0s 6ms/step - loss: 6.7763
Epoch 309/1000
1/1 [==============================] - 0s 6ms/step - loss: 6.7424
Epoch 310/1000
1/1 [==============================] - 0s 5ms/step - loss: 6.7086
Epoch 311/1000
1/1 [==============================] - 0s 6ms/step - loss: 6.6750
Epoch 312/1000
1/1 [==============================] - 0s 6ms/step - loss: 6.6415
Epoch 313/1000
1/1 [========

1/1 [==============================] - 0s 5ms/step - loss: 4.0638
Epoch 403/1000
1/1 [==============================] - 0s 10ms/step - loss: 4.0400
Epoch 404/1000
1/1 [==============================] - 0s 5ms/step - loss: 4.0163
Epoch 405/1000
1/1 [==============================] - 0s 4ms/step - loss: 3.9927
Epoch 406/1000
1/1 [==============================] - 0s 6ms/step - loss: 3.9693
Epoch 407/1000
1/1 [==============================] - 0s 7ms/step - loss: 3.9459
Epoch 408/1000
1/1 [==============================] - 0s 7ms/step - loss: 3.9226
Epoch 409/1000
1/1 [==============================] - 0s 6ms/step - loss: 3.8994
Epoch 410/1000
1/1 [==============================] - 0s 5ms/step - loss: 3.8764
Epoch 411/1000
1/1 [==============================] - 0s 5ms/step - loss: 3.8534
Epoch 412/1000
1/1 [==============================] - 0s 4ms/step - loss: 3.8305
Epoch 413/1000
1/1 [==============================] - 0s 5ms/step - loss: 3.8078
Epoch 414/1000
1/1 [======================

1/1 [==============================] - 0s 6ms/step - loss: 2.1475
Epoch 504/1000
1/1 [==============================] - 0s 5ms/step - loss: 2.1331
Epoch 505/1000
1/1 [==============================] - 0s 5ms/step - loss: 2.1187
Epoch 506/1000
1/1 [==============================] - 0s 5ms/step - loss: 2.1043
Epoch 507/1000
1/1 [==============================] - 0s 6ms/step - loss: 2.0901
Epoch 508/1000
1/1 [==============================] - 0s 4ms/step - loss: 2.0760
Epoch 509/1000
1/1 [==============================] - 0s 5ms/step - loss: 2.0619
Epoch 510/1000
1/1 [==============================] - 0s 4ms/step - loss: 2.0479
Epoch 511/1000
1/1 [==============================] - 0s 5ms/step - loss: 2.0339
Epoch 512/1000
1/1 [==============================] - 0s 5ms/step - loss: 2.0201
Epoch 513/1000
1/1 [==============================] - 0s 5ms/step - loss: 2.0063
Epoch 514/1000
1/1 [==============================] - 0s 6ms/step - loss: 1.9926
Epoch 515/1000
1/1 [=======================

1/1 [==============================] - 0s 5ms/step - loss: 1.0380
Epoch 605/1000
1/1 [==============================] - 0s 4ms/step - loss: 1.0301
Epoch 606/1000
1/1 [==============================] - 0s 7ms/step - loss: 1.0222
Epoch 607/1000
1/1 [==============================] - 0s 5ms/step - loss: 1.0144
Epoch 608/1000
1/1 [==============================] - 0s 8ms/step - loss: 1.0067
Epoch 609/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.9990
Epoch 610/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.9913
Epoch 611/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.9837
Epoch 612/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.9762
Epoch 613/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.9687
Epoch 614/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.9612
Epoch 615/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.9538
Epoch 616/1000
1/1 [======================

1/1 [==============================] - 0s 6ms/step - loss: 0.4591
Epoch 706/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.4552
Epoch 707/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4513
Epoch 708/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.4475
Epoch 709/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.4437
Epoch 710/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4399
Epoch 711/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.4362
Epoch 712/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4324
Epoch 713/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.4287
Epoch 714/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.4251
Epoch 715/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4214
Epoch 716/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.4178
Epoch 717/1000
1/1 [=======================

1/1 [==============================] - 0s 5ms/step - loss: 0.1857
Epoch 807/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.1840
Epoch 808/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.1822
Epoch 809/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.1805
Epoch 810/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.1788
Epoch 811/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.1771
Epoch 812/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.1755
Epoch 813/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.1738
Epoch 814/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.1722
Epoch 815/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.1706
Epoch 816/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.1690
Epoch 817/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.1674
Epoch 818/1000
1/1 [======================

1/1 [==============================] - 0s 5ms/step - loss: 0.0686
Epoch 908/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.0679
Epoch 909/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.0672
Epoch 910/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.0665
Epoch 911/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.0658
Epoch 912/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.0651
Epoch 913/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.0645
Epoch 914/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.0638
Epoch 915/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.0631
Epoch 916/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.0625
Epoch 917/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.0618
Epoch 918/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.0612
Epoch 919/1000
1/1 [=======================

In [15]:
hist.history['loss']

[22704.56640625,
 21255.859375,
 20086.47265625,
 19133.556640625,
 18276.27734375,
 17443.900390625,
 16622.09765625,
 15811.955078125,
 15016.4189453125,
 14237.9794921875,
 13478.474609375,
 12739.2626953125,
 12021.369140625,
 11325.5908203125,
 10652.5751953125,
 10002.8505859375,
 9376.8515625,
 8774.931640625,
 8197.357421875,
 7644.31640625,
 7115.8935546875,
 6612.0810546875,
 6132.7607421875,
 5677.7080078125,
 5246.58740234375,
 4838.96435546875,
 4454.3095703125,
 4092.01025390625,
 3751.391357421875,
 3431.727783203125,
 3132.26611328125,
 2852.23828125,
 2590.876708984375,
 2347.42333984375,
 2121.140869140625,
 1911.3062744140625,
 1717.2177734375,
 1538.1849365234375,
 1373.526611328125,
 1222.56103515625,
 1084.6025390625,
 958.9559326171875,
 844.9191284179688,
 741.7807006835938,
 648.8279418945312,
 565.3507080078125,
 490.6514587402344,
 424.04986572265625,
 364.8923034667969,
 312.5567321777344,
 266.45538330078125,
 226.03701782226562,
 190.78567504882812,
 160.2

In [16]:
%matplotlib
import matplotlib.pyplot as plt

Using matplotlib backend: <object object at 0x000001BDEF4DF620>


In [ ]:
plt.plot('Epochs', 'Loss', data=hist.history['loss'])

In [ ]:
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.plot(hist.history['loss']);

In [1]:
!conda clean -tipsy

usage: conda-script.py clean [-h] [-a] [-i] [-p] [-t] [-f]
                             [-c [TEMPFILES ...]] [-l] [-d] [--json] [-q] [-v]
                             [-y]
conda-script.py clean: error: argument -p/--packages: ignored explicit argument 'sy'
